language: python

dist: bionic

# https://devguide.python.org/#branchstatus
python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install bandit flake8 python-coveralls coverage liccheck
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - pip install dist/rssgen*

script:
  - make test
  - liccheck -s .licenses.ini
  - python -m rssgen
  - python -m rssgen atom
  - python -m rssgen rss

after_success:
   - coveralls
